2021/12/10 06:55:32 [error] 40879#0: upsync_del_peer: upstream "test" cannot delete all peers
2021/12/10 06:55:32 [error] 40879#0: upsync_process: upstream del peers failed
2021/12/10 06:57:10 [notice] 40970#0: signal process started
2021/12/10 06:57:10 [error] 40879#0: [WARN]:upsync_clear_all_events: on 40879 
2021/12/10 06:57:12 [error] 40971#0: upsync_del_peer: upstream "test" cannot delete all peers
2021/12/10 06:57:12 [error] 40971#0: upsync_process: upstream del peers failed
2021/12/10 07:07:43 [emerg] 42935#0: no servers are inside upstream in /home/ubuntu/soft/basic/tengine/conf/sites-enabled/cook-fa.conf:7
2021/12/10 07:07:46 [emerg] 42940#0: no servers are inside upstream in /home/ubuntu/soft/basic/tengine/conf/sites-enabled/cook-fa.conf:7
2021/12/10 07:09:47 [error] 40971#0: [WARN]:upsync_clear_all_events: on 40971 
2021/12/10 07:09:56 [emerg] 42969#0: open() "/tmp/upsync_backend/cook-fa.conf" failed (2: No such file or directory) in /home/ubuntu/soft/basic/tengine/conf/sites-enabled/cook-fa.conf:6
2021/12/10 07:10:20 [emerg] 42978#0: no servers are inside upstream in /home/ubuntu/soft/basic/tengine/conf/sites-enabled/cook-fa.conf:7
2021/12/10 07:14:18 [error] 43125#0: upsync_del_peer: upstream "test" cannot delete all peers
2021/12/10 07:14:18 [error] 43125#0: upsync_process: upstream del peers failed
2021/12/10 07:14:29 [error] 43125#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "192.168.6.110:8080"
2021/12/10 07:14:32 [error] 43125#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "192.168.6.110:8080"
2021/12/10 07:14:33 [error] 43125#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "192.168.6.110:8080"
2021/12/10 07:15:35 [error] 43125#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "192.168.6.110:8080"
2021/12/10 07:15:36 [error] 43125#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "192.168.6.110:8080"
2021/12/10 07:15:37 [error] 43125#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "192.168.6.110:8080"
2021/12/10 07:19:46 [notice] 43298#0: signal process started
2021/12/10 07:19:46 [error] 43125#0: [WARN]:upsync_clear_all_events: on 43125 
2021/12/10 07:19:47 [error] 43299#0: upsync_del_peer: upstream "test" cannot delete all peers
2021/12/10 07:19:47 [error] 43299#0: upsync_process: upstream del peers failed
2021/12/10 07:22:07 [notice] 43324#0: signal process started
2021/12/10 07:22:07 [error] 43299#0: [WARN]:upsync_clear_all_events: on 43299 
2021/12/10 07:23:57 [notice] 43402#0: signal process started
2021/12/10 07:23:57 [error] 43325#0: [WARN]:upsync_clear_all_events: on 43325 
2021/12/10 07:23:58 [error] 43403#0: upsync_del_peer: upstream "test" cannot delete all peers
2021/12/10 07:23:58 [error] 43403#0: upsync_process: upstream del peers failed
2021/12/10 07:24:08 [error] 43403#0: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "192.168.6.110:8080"
2021/12/10 07:24:23 [notice] 43454#0: signal process started
2021/12/10 07:24:23 [error] 43403#0: [WARN]:upsync_clear_all_events: on 43403 
2021/12/10 07:24:53 [error] 43403#0: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.6.53, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "192.168.6.110:8080"
2021/12/10 07:25:38 [error] 43455#0: [WARN]:upsync_clear_all_events: on 43455 
